[project]
name = "sistua-o-de-aprendizado-sistema-de-ecommerce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Erick", email = "erick_r_soares@estudante.sesisenai.org.br" }
]
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
]

[project.scripts]
sistua-o-de-aprendizado-sistema-de-ecommerce = "sistua_o_de_aprendizado_sistema_de_ecommerce:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
